spring.application.name=scms

# ---------------- Server ----------------
server.port=${PORT:8080}
server.servlet.context-path=/

# ---------------- MySQL Database ----------------
spring.datasource.url=jdbc:postgresql://ep-bitter-sun-b4tfu0jr-pooler.c-6.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_UZNwzgxtqv70&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UZNwzgxtqv70
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------- JPA / Hibernate ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ---------------- JWT ----------------
jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration.ms=86400000
jwt.refresh-expiration.ms=604800000

# ---------------- File Upload ----------------
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads
app.storage.provider=local
# provider options: local | cloudinary

cloudinary.cloud-name=dzrjltnpk
cloudinary.api-key=925677612485317
cloudinary.api-secret=Re5ZwUSPAvGeL3MXs17l1euoZd4
# ---------------- Mail (for password reset) ----------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=no.reply.lms0@gmail.com
spring.mail.password=cankyqspyejinkxh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ---------------- CORS ----------------
# ---------------- CORS ----------------
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,https://jana-jagoran-club.vercel.app
app.backend.url=https://jana-jagoran-club-scms.onrender.com

# ---------------- Club Info ----------------
app.club.name=Jana Jagoran Club
app.member.monthly-fee=50.00

# ---------------- Logging ----------------
logging.level.com.janajagoran.scms=INFO
logging.level.org.springframework.security=WARN
