package com.janajagoran.scms.enums;

/** Fixed catalog of audit-logged actions -- keeps audit_log.action consistent and filterable. */
public enum AuditAction {
    MEMBER_REGISTERED,
    MEMBER_APPROVED,
    MEMBER_REJECTED,
    LOGIN,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    PROFILE_UPDATED,
    MEMBER_ACTIVATED,
    MEMBER_DEACTIVATED,
    DESIGNATION_CREATED,
    DESIGNATION_UPDATED,
    DESIGNATION_ACTIVATED,
    DESIGNATION_DEACTIVATED,
    DESIGNATION_ASSIGNED,
    DESIGNATION_RELEASED,
    SECRETARY_ASSIGNED,
    SECRETARY_APPROVED,
    PRESIDENT_ASSIGNED,
    PRESIDENT_APPROVED,
    ROLE_CHANGED,
    APPROVAL_GRANTED,
    APPROVAL_REJECTED,
    PHOTO_SUBMITTED,
    PHOTO_APPROVED,
    PHOTO_REJECTED
}
